modified tfvars.json.sample for mp-eks (#266)
Minor change:

added `<YOUR_AWS_ACCT_PREFIX>` to `"tsb_fqdn": "<YOUR UNIQUE PREFIX NAME
TO BE CREATED>.<YOUR_AWS_ACCT_PREFIX>.sandbox.tetrate.io"` in
`mp-eks-cp-1aks-1eks-2gke.tfvars.json.sample` file to avoid this error:
```
Error: no matching Route53Zone found
│
│   with module.register_fqdn.data.aws_route53_zone.zone,
│   on ../../../modules/aws/register_fqdn/main.tf line 1, in data "aws_route53_zone" "zone":
│    1: data "aws_route53_zone" "zone" {
```

required for usage:
```
# Build full demo
make tsb
```

Co-authored-by: Alex Skvo <alexskvo@Alexs-MacBook-Pro.local>